version: '3'
services:
  nest-api:
    container_name: nest-api
    # build: 
    #   context: .
    image: nhatminhcr77/blog-backend
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    environment:
      - DATABASE_URL=mysql://root:QTrJfl0R&64@mysql_db:3306/db_blog
    networks:
      - node-network

  mysql_db:
    image: mysql
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=QTrJfl0R&64
      - MYSQL_DATABASE=db_blog
    env_file:
      - .env
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network

volumes:
  mysql_db:
    driver: local
networks:
  node-network: